stages:
  - build

  - deploy

image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

before_script:
  #- docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY #login docker hub
  - docker login -u https://gitlab.tanitweb.tn/ -p GR13489418v3TVLwqEH-w8ypsqtVf 
build:
  stage: build
  before_script:
  - docker login -u https://gitlab.tanitweb.tn/ -p GR13489418v3TVLwqEH-w8ypsqtVf #login docker hub
  
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push  #image name (composer)


  deploy:
    stage: deploy
    before_script:
    -  #connexion ssh pour le serveur ou je ais deployer l'image
    script:
      - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      - ssh user@server "docker-compose -f /path/to/docker-compose.yml pull && docker-compose -f /path/to/docker-compose.yml up -d"
