services:
  database:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: club
  mysql:
    image: mysql:8.0
    container_name: project_mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD: project
      MYSQL_DATABASE: project
      MYSQL_USER: project
      MYSQL_PASSWORD: project
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: project_phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "81:80"
    networks:
      - project_net

  web:
    build: .
    container_name: project_web
    volumes:
      - ./:/var/www/html/
      - ./.docker/symfony.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "80:80"
    depends_on:
      - mysql
    networks:
      - project_net

  mailhog:
    image: mailhog/mailhog
    container_name: project_mailhog
    ports:
      - "1025:1025" # smtp server
      - "8025:8025" # web ui
    networks:
      - project_net

networks:
  project_net:
    driver: bridge